Add usage for bak script

diff --git a/scripts/bak b/scripts/bak
--- a/scripts/bak
+++ b/scripts/bak
@@ -3,11 +3,19 @@
 UNIX_TIMESTAMP=
 FNAMES=()
 
+usage() {
+	echo "Usage: bak [-u | --unix] [<filenames>]"
+}
+
 while [ "$1" != "" ]
 do
 	case $1 in
-		-u | --unix-timestamp )
+		-u | --unix )
 			UNIX_TIMESTAMP=1
+			;;
+		-h | --help )
+			usage
+			exit 0
 			;;
 		* )
 			FNAMES+=("$1")
@@ -20,7 +28,8 @@ for fn in "${FNAMES[@]}"
 do
 	if [ ! -f $fn ]
 	then
-		echo "file not found: $fn"
+		>&2 echo "ERROR: File not found: \"$fn\""
+		exit 1
 	else
 		if [ $UNIX_TIMESTAMP ]
 		then
